name: Build Android AAB

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java (Temurin 17)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK packages
        run: |
          sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Remove Windows-only local.properties (use SDK from runner)
        run: rm -f android/local.properties

      - name: Write signing keystore from secret
        env:
          RELEASE_KEYSTORE_BASE64: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}
        run: |
          if [ -z "$RELEASE_KEYSTORE_BASE64" ]; then
            echo "RELEASE_KEYSTORE_BASE64 secret not set." && exit 1
          fi
          mkdir -p android/app
          echo "$RELEASE_KEYSTORE_BASE64" | base64 -d > android/app/release-key.jks

      - name: Write key.properties from secrets
        env:
          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: |
          if [ -z "$RELEASE_KEYSTORE_PASSWORD" ] || [ -z "$RELEASE_KEY_ALIAS" ] || [ -z "$RELEASE_KEY_PASSWORD" ]; then
            echo "Signing secrets not set (RELEASE_KEYSTORE_PASSWORD/RELEASE_KEY_ALIAS/RELEASE_KEY_PASSWORD)." && exit 1
          fi
          cat > android/key.properties << 'EOF'
          storeFile=app/release-key.jks
          storePassword=${RELEASE_KEYSTORE_PASSWORD}
          keyAlias=${RELEASE_KEY_ALIAS}
          keyPassword=${RELEASE_KEY_PASSWORD}
          EOF

      - name: Flutter pub get
        run: flutter pub get

      - name: Build signed release AAB
        run: flutter build appbundle --release --verbose

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: bajetimor-signed-aab
          path: build/app/outputs/bundle/release/app-release.aab